2022-04-01 11:02:20,872 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2022-04-01 11:02:20,877 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from C:\Users\LenovoPC\AppData\Local\Programs\Python\Python310\lib\site-packages\instabot\bot\bot.py
2022-04-01 11:02:20,880 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2022-04-01 11:02:21,291 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [429]>
2022-04-01 11:02:21,292 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"Please wait a few minutes before you try again.","status":"fail"}'
2022-04-01 11:02:21,293 - instabot version: 0.117.0 (api) - ERROR - Request returns 429 error!
2022-04-01 11:02:21,297 - instabot version: 0.117.0 (api) - WARNING - That means 'too many requests'. I'll go to sleep for 5 minutes.
2022-04-01 11:07:21,657 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [429]>
2022-04-01 11:07:21,658 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"Please wait a few minutes before you try again.","status":"fail"}'
2022-04-01 11:07:21,658 - instabot version: 0.117.0 (api) - ERROR - Request returns 429 error!
2022-04-01 11:07:21,664 - instabot version: 0.117.0 (api) - WARNING - That means 'too many requests'. I'll go to sleep for 10 minutes.
2022-04-01 11:10:51,768 - instabot version: 0.117.0 (bot_checkpoint) - DEBUG - Saving Checkpoint file to: D:\Django Multiplatform\Blog_Post/config/sonashimehru.checkpoint
2022-04-01 11:10:51,769 - instabot version: 0.117.0 (bot) - INFO - Total requests: 35
